#################################
#####         语言          #####
#################################
lang:
  cn: "lang_cn.yml"

#################################
#####         配置          #####
#################################
#掉落范围提示的范围大小,>=0.0
tipRange: 8.0

#################################
#####     物品获取类型      #####
#################################
items:
  zombie_drop:
    - "default:default all:1-1"